"""empty message

Revision ID: 3c564b3f3896
Revises: 48e6ed83e9fb
Create Date: 2023-12-21 10:25:14.006962

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c564b3f3896'
down_revision = '48e6ed83e9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clothes', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
